version: '3.5'

services:
  flaskapp:
    build: ./web
    restart: always
    expose:
      - "8000"
    volumes:
      - ./web:/home/website-v3/app/web

   # Define the redis NGINX forward proxy container
  nginx:
    # build the nginx Dockerfile: http://bit.ly/2kuYaIv
    build: nginx/
    restart: always

    # Expose port 80 to the host machine
    ports:
      - "80:80"

    # The Flask application needs to be available for NGINX to make successful proxy requests
    depends_on:
      - flaskapp

  redis:
    build: ./redisdb
    restart: always 
    expose:
      - "6379"

  pytorch:
    build: ./pytorch_server/
    restart: always