"""posts link

Revision ID: b234033f901d
Revises: f33c34a4cccf
Create Date: 2018-07-12 12:47:49.772703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b234033f901d'
down_revision = 'f33c34a4cccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('link', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'link')
    # ### end Alembic commands ###
